# Generated by Django 3.1.2 on 2020-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='cartas_atk',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartas',
            name='cartas_def',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartas',
            name='cartas_descricao',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AddField(
            model_name='cartas',
            name='cartas_nome',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
